/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Practica_CRUD;
import io.javalin.Javalin;
import io.javalin.plugin.rendering.JavalinRenderer;
import io.javalin.plugin.rendering.template.JavalinThymeleaf;

import java.sql.SQLException;

import Practica_CRUD.encapsulations.Usuario;
import Practica_CRUD.services.BaseDatos;
import Practica_CRUD.services.UsuarioServices;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws SQLException {
        System.out.println(new App().getGreeting());
        //Tienda tienda = Tienda.getInstance();

        Javalin app = Javalin.create(config -> {
            config.addStaticFiles("/templates");
        }).start(getHerokuAssignedPort());
        
        BaseDatos.getInstance().startDB();
        // BaseDatos.getInstance().getConnection();
        Usuario admin = new Usuario("admin", "admin", "admin");
        
        if(UsuarioServices.getInstance().find("admin") == null){
            UsuarioServices.getInstance().crear(admin);
        }

        JavalinRenderer.register(JavalinThymeleaf.INSTANCE, ".html");
        new ControladoraRutas(app).aplicarRutas();

    }

    static int getHerokuAssignedPort() {
        ProcessBuilder processBuilder = new ProcessBuilder();
        if (processBuilder.environment().get("PORT") != null) {
            return Integer.parseInt(processBuilder.environment().get("PORT"));
        }
        return 7000; //Retorna el puerto por defecto en caso de no estar en Heroku.
    }
}
